// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYfMTm8yJVeQwexOqk5hjsZNtgjyZzeM',
    appId: '1:290768615588:web:c912d09a5454517a188e31',
    messagingSenderId: '290768615588',
    projectId: 'presently-e0a79',
    authDomain: 'presently-e0a79.firebaseapp.com',
    storageBucket: 'presently-e0a79.firebasestorage.app',
    measurementId: 'G-88H3372281',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoerJvRPJhaiB9hZ7ZXg4e-6Y8O_Z-IFQ',
    appId: '1:290768615588:android:f56a09544ca20fb8188e31',
    messagingSenderId: '290768615588',
    projectId: 'presently-e0a79',
    storageBucket: 'presently-e0a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvFJNnNdSMyZDqSM92GFYHTA8aJcEKmjU',
    appId: '1:290768615588:ios:a5398da94f379288188e31',
    messagingSenderId: '290768615588',
    projectId: 'presently-e0a79',
    storageBucket: 'presently-e0a79.firebasestorage.app',
    iosBundleId: 'com.example.presently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvFJNnNdSMyZDqSM92GFYHTA8aJcEKmjU',
    appId: '1:290768615588:ios:a5398da94f379288188e31',
    messagingSenderId: '290768615588',
    projectId: 'presently-e0a79',
    storageBucket: 'presently-e0a79.firebasestorage.app',
    iosBundleId: 'com.example.presently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYfMTm8yJVeQwexOqk5hjsZNtgjyZzeM',
    appId: '1:290768615588:web:c1e850cb267e25af188e31',
    messagingSenderId: '290768615588',
    projectId: 'presently-e0a79',
    authDomain: 'presently-e0a79.firebaseapp.com',
    storageBucket: 'presently-e0a79.firebasestorage.app',
    measurementId: 'G-8EQZZX57DK',
  );
}
